### ISSUE TITLE
LICENSE missing

### ISSUE THREAD

**Issue by andrecastro0o** [Abbe98/thor#2]
Dear @nemobis & @Abbe98  I came across this SPARQL interface and I would love to use it a project I am working on.
I would like to fork it, to make some changes, namely style, no startup use dialogs.
Although in the documentation it says `this SPARQL Editor is Open Source `  I cannot find its license, so that I can give credit where credit is due!! 

Thanks.
BTW. This is a great library and interface!!

**Comment by Abbe98** [comment]
Thanks to pointing this out I have now added a LICENSE file.
